### ISSUE TITLE
Upgrade Flow to the latest version

### ISSUE THREAD

**Issue by mourner** [mapbox/mapbox-gl-js#11426]
The Flow version we currently use for type checking is nearly [3 years old](https://github.com/facebook/flow/releases/tag/v0.103.0) and critically outdated.

- It's extremely slow. Running flow check after changing one line of code takes 1+ min, which is unacceptable for iterative development. 
- It's buggy. There have been hundreds of bugfixes since.
- It's not sound. Many typing errors are silently ignored.
- The errors are often unhelpful.

The latest version (v0.170) has [radically better architecture](https://medium.com/flow-type/types-first-a-scalable-new-architecture-for-flow-3d8c7ba1d4eb) that allows it to be orders of magnitude faster, while fixing numerous soundness and stability issues. Upgrading to it would allow us to iterate on GL JS much faster, especially when doing bigger refactoring projects. Additionally, if we commit to switching to TypeScript in the future, having better type coverage will make it much easier. 

But it's not easy — simply updating the version produces several thousand type errors, some due to increased strictness and soundness, and some due to typing mistakes being silently ignored in the current version (with #11400 as an example of this). 

Here's my plan for a gradual upgrade:

- [x] Type matrix and vector calculations properly — it's  a major source of errors in the newer versions. #11400
- [x] Upgrade to v0.130, redoing #9188 — now many properties that can be deleted need to be properly typed as optional, a common mistake throughout our codebase. #11431
- [x] Upgrade to v0.131 that enables `unsafe-addition` for safer arithmetic code. #11436 
- [x] Upgrade to v0.132 that now forbids implicitly using `any` types, producing a ton of errors on code which is currently typed incorrectly but silently ignored. #11456
- [x] Upgrade to v0.142 with type_first mode disabled, the latest version where you can do that. #11456
- [x] **Type-first sprint:** gradually upgrade the codebase to support `type_first=true` architecture.
- [ ] Once type-first mode works, turn it on and upgrade to the latest version.

### Type-first sprint

  - [ ] Make a list of all JS files in `src/`, and assign batches of files across people participating in the sprint.
  - [ ] For each file, remove the `type_first=false` line in `.flowconfig`, then run `flow codemod annotate-exports --write --repeat <path>` (see [codemod docs](https://flow.org/en/docs/cli/annotate-exports/))
  - [ ] Make sure generated types make sense, fix if necessary. 
  - [ ] Discard `.flowconfig` changes and make sure `test-flow` passes.
  - [ ] PR the changes for a batch of files to `main`.
