### ISSUE TITLE
Upgrade Flow to the latest version

### ISSUE THREAD

**Issue by mourner** [mapbox/mapbox-gl-js#12194]
This is a continuation of #11426. Upgrading Flow to a more recent version with a new architecture was a massive improvement that fixed a critical flaw in GL JS development, but we're still stuck on a specific version we can't upgrade continuously because it needs further substantial typing improvements across the codebase. This ticket will track this second stage of the upgrade work.

This also makes a potential transition to TypeScript in the future much easier, since more recent versions of Flow are gradually transitioning to a [new way of inferring types](https://medium.com/flow-type/introducing-local-type-inference-for-flow-6af65b7830aa) which brings it closer to other type systems such as TypeScript.

**Version used:** v0.142.0 (Jan 2021).
**Latest version:** v0.185.2 (as of Aug 2022).

#### Milestones

A few possible milestones judging by the changelog entries (will be updated as we go).

- [ ] [v0.143.0](https://github.com/facebook/flow/releases/tag/v0.143.0) — introduces much more strict and robust handling of library definitions (external dependencies, etc.), a part of which was previously ignored due to a bug. Produces a ton of errors to be fixed.
- [ ] [v0.146.0](https://github.com/facebook/flow/releases/tag/v0.146.0) — stricter refinements, likely exposing a bunch of new errors.
- [ ] [v0.155.0](https://github.com/facebook/flow/releases/tag/v0.153.0) — much stricter typing of `this` across these 3 releases produces new errors.
- [ ] [v0.163.0](https://github.com/facebook/flow/releases/tag/v0.163.0) — deprecates `*` types, which will need to be replaced with new errors addressed.
- [ ] [v0.185.0](https://github.com/facebook/flow/releases/tag/v0.185.0) — switches to a completely new local inference mode, which will likely require much stricter typing of variables across the codebase (there's a codemod for it that may help though).
