### ISSUE TITLE
Fix v8 test suite failures

### ISSUE THREAD

**Issue by lucaswoj** [mapbox/mapbox-gl-js#1326]
#1325 will fix the runtime exceptions when running the test suite (yikes!)

Presently, in the `v8` branch, failures against test suite for the following properties

 - [x] `circle-*` (fixed by #1320)
 - [x] `line-*` (tracked in #1328 #1329 #1330; related to #1313)
 - [x] `text-*` (tracked in #1327)
 - [x] `icon-*` (tracked in #1327)
 - [x] `fill-*` (mysteriously fixed by #1320)

**Comment by lucaswoj** [comment]
Test output after applying #1320 and #1325 https://gist.github.com/lucaswoj/98c31aaf3a7f1c77abb0

**Comment by lucaswoj** [comment]
Slightly easier to read list of failing tests at https://gist.github.com/lucaswoj/b82cf4794f4b70bdb639

**Comment by lucaswoj** [comment]
Wow! Nice work @ansis :fireworks:
