### ISSUE TITLE
iOS next sprint

### ISSUE THREAD

**Issue by incanus** [mapbox/mapbox-gl-js#226]
Latest progress here: https://github.com/mapbox/hey/issues/1326

Next goals for me are: 
- [x] Get fills working - I believe this is the stencil buffer issue (#222). 
- [x] Get things running on device. @kkaefer is this just stencil buffer issues, or something else? Do we know? I'm not sure if we have any leads here, so shout out any thoughts you have and I can start investigating. I'm shooting for retina iPad so that we can be sure things work on the most demanding graphical hardware. 
- [ ] Work off of a more global tileset. This relies on #218 public font server. Exploring other areas beyond DC unlocks customer demo potential as well as possibly uncovers more edge cases. 
- [ ] Solve web worker problem. Right now, we don't use them and fetch/parse vector tiles in the UI thread. Whether this means calling out to async Cocoa code or just porting web workers remains to be seen. (https://github.com/mapbox/llmr/issues/232)

I'm in the <500 LOC range for all the native stuff I've done so far, so we're not making significant throwaway investments in Ejecta, sticking with JS, Cocoa bindings etc. This is still good work to be doing. 

/cc @gundersen @yhahn
