### ISSUE TITLE
Improve query*Features documentation

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-js#2429]
The following caveats for feature querying were included in [the documentation for the `featuresCallback` for `featuresAt` / `featuresIn`](https://github.com/mapbox/mapbox-gl-js/blob/v0.15.0/js/ui/map.js#L914-L919):

```
 * Note: because features come from vector tiles or GeoJSON data that is converted to vector tiles internally, the returned features will be:
 *
 * 1. Truncated at tile boundaries.
 * 2. Duplicated across tile boundaries.
 *
 * For example, suppose there is a highway running through your rectangle in a `featuresIn` query. `featuresIn` will only give you the parts of the highway feature that lie within the map tiles covering your rectangle, even if the road actually extends into other tiles. Also, the portion of the highway within each map tile will come back as a separate feature.
```

We should restore and adapt this text for the documentation for queryRenderedFeatures and querySourceFeatures.

**EDIT: The scope of this ticket has expanded. Please see https://github.com/mapbox/mapbox-gl-js/issues/2429#issuecomment-214899878**

**Comment by jfirebaugh** [comment]
Another thing to document is the decision in https://github.com/mapbox/mapbox-gl-js/issues/2321 about the behavior for wrapped features.

**Comment by ansis** [comment]
Another thing to document is that the order of the features is top-down based on the style.

**Comment by lucaswoj** [comment]
# Todo

 - [ ] restore query method caveats https://github.com/mapbox/mapbox-gl-js/issues/2429#issue-147903525
 - [ ] document is that the order of the features is top-down based on the style. https://github.com/mapbox/mapbox-gl-js/issues/2429#issuecomment-209171384
 - [ ] document is the decision in #2321 about the behavior for wrapped features
 - [ ] document that these methods only operate on visible features 
 - [ ] explain the difference between `querySourceFeatures` and `queryRenderedFeatures`
