### ISSUE TITLE
Support custom source types

### ISSUE THREAD

**Issue by lucaswoj** [mapbox/mapbox-gl-js#3326]
This is an umbrella issue meant to track the various moving pieces of getting our custom source API ready for primetime. I created a project for this but am having trouble adding issues to it. 

 - [ ]  [Support custom attribution strings](https://github.com/mapbox/mapbox-gl-js/issues/1485)
 - [ ] [Refactor "Worker", "Dispatcher", "Actor" into a general purpose "PooledWorker" utility](https://github.com/mapbox/mapbox-gl-js/issues/3034)
 - [ ] [Refactor source interface to better accommodate non-tiled sources](https://github.com/mapbox/mapbox-gl-js/issues/3186)
 - [ ] [Refactor `GeoJSONSource` as a composition `VectorTileSource`](https://github.com/mapbox/mapbox-gl-js/issues/3051)
 - [ ] Add a `Map#addCustomSource(...)` method
 - [ ] [Document the custom source API](https://github.com/mapbox/mapbox-gl-js/issues/2920)
 - [ ] [Allow sources to specify their own validation logic](https://github.com/mapbox/mapbox-gl-js/issues/3003)

**Comment by lucaswoj** [comment]
👉  https://github.com/mapbox/mapbox-gl-js/projects/2

**Comment by remster** [comment]
Hey Lucas. I just forked mapbox-gl-js to achieve something similar. I need to override some of the VectorTileWorkerSource's behaviour...
The reference to which is hardcoded [here](https://github.com/mapbox/mapbox-gl-js/blob/master/js/source/worker.js#L20) as i type this and will hopefully remain in vicinity when you hopefully read this. 

I understand that ultimately the ambition is for this mapping:
`        this.workerSourceTypes = {
            vector: VectorTileWorkerSource,
            geojson: GeoJSONWorkerSource
        };`
to be supplied (in one gulp or increments) by the client (whoever constructed the mapboxgl.Map(...)) <- possibly in its c'tor params.

I am asking because as much as i can survive on my fork until your work is complete, i'd hate making wrong assumptions about where this goes. I've been trying to deduct it from your work's outline, say #3034, perhaps didn't read carefully enough, but couldn't really reassure myself.

BTW: is it in active development at present? 
Perhaps there is something i could help with.

**Comment by lucaswoj** [comment]
Thanks for asking @remster. You can see the outstanding tasks for this refactor in in https://github.com/mapbox/mapbox-gl-js/projects/2. If you're serious about tackling any of those issues, let me know and I'll be sure to connect you with whatever help/resources you need.

**Comment by lucaswoj** [comment]
Based on current internal priorities, we aren't actively developing the custom source API right now. You can see our roadmap here: https://www.mapbox.com/mapbox-gl-js/roadmap/
