### ISSUE TITLE
Merge "mapbox-gl-function" repo into this repo

### ISSUE THREAD

**Issue by lucaswoj** [mapbox/mapbox-gl-js#3793]
ref #3656 

# Todo

 - [ ] move over files
 - [ ] set up `mapbox-gl-function` npm package to be published from `mapbox-gl-js` repo
 - [ ] migrate `mapbox-gl-function` issues & PRs
 - [ ] mark the `mapbox-gl-function` github repo as deprecated

**Comment by jfirebaugh** [comment]
Monorepo'ing this is good, but let's keep publishing this as an independent package rather than merging it at the API level. That helps keep a clear separation of concerns and allows us to version the function API independently of the mapbox-gl version.

**Comment by lucaswoj** [comment]
Sounds like a good plan @jfirebaugh. Updated the **Todo** list.
