### ISSUE TITLE
Merge the "mapbox-gl-test-suite" repo into this repo

### ISSUE THREAD

**Issue by lucaswoj** [mapbox/mapbox-gl-js#3795]
ref #3656 

# Todo

 - [ ] move over files
 - [ ] investigate using `git-lfs` for all images & binary test fixtures 
 - [ ] migrate `mapbox-gl-test-suite` issues & PRs
 - [ ] configure `mapbox-gl-native` to pull test-suite files from `mapbox-gl-js` package
 - [ ] mark the `mapbox-gl-test-suite` github repo as deprecated
 - [ ] mark the `mapbox-gl-test-suite` npm package as deprecated

**Comment by mourner** [comment]
For the test suite, I think we should copy over without preserving the git history - it's now so huge that a clone can take half an hour. We can look up history in the archived repo if needed.

Also, should we consider using something like git-lfs for all the images to prevent the repo from bloating in future?
