### ISSUE TITLE
Merge "feature-filter" repo into this repo

### ISSUE THREAD

**Issue by lucaswoj** [mapbox/mapbox-gl-js#3813]
ref #3656 

# Todo

 - [ ] move over files
 - [ ] set up `feature-filter` npm package to be published from `mapbox-gl-style-spec` repo
 - [ ] migrate `feature-filter` issues & PRs
 - [ ] mark the `feature-filter` github repo as deprecated
