### ISSUE TITLE
WWDC native style compatibility

### ISSUE THREAD

**Issue by mourner** [mapbox/mapbox-gl-js#401]
What needs to be done in llmr to fully support the latest Outdoors style for native (converted with gl-style script):
- [x] @yhahn `icon` bucket property (e.g. to use `maki` field for pois) https://github.com/mapbox/mapbox-gl-native/pull/196 — to avoid creating LOTS of poi buckets (one for each poi type). Also see https://github.com/mapbox/mapbox-gl-native/issues/300
- [x] @ansis `strokeBlur` (which will be `text-halo-blur`) — for some label effects
- [ ] @ansis composite blurring: `prerender`, `prerender-size`, `prerender-blur` https://github.com/mapbox/llmr/pull/424 https://github.com/mapbox/mapbox-gl-native/pull/192 — for contour and hillshade blurring
- [x] @yhahn token replacement system (`"text-field": '{{name}}'` instead of just `'name'`) https://github.com/mapbox/mapbox-gl-native/commit/c5fd7a0cddbf6825e3947bfbff418730b288b7bb — for contour labels
- [x] @mourner complex filters (and, or, not, <=, <, etc.) https://github.com/mapbox/llmr/pull/430 https://github.com/mapbox/llmr/issues/407
- [x] @mourner 300ms default transition for everything

In addition, there are following issues with rendering Outdoors to be fixed:
- [x] @mourner fix stops function not using closest stop value for zooms after last stop and before first stop
- [x] @mourner translate properties are broken https://github.com/mapbox/llmr/issues/378
- [ ] @mourner rendering order is messed up — some casings render on top of roads
- [x] @mourner pois not appearing at all
- [x] @ansis point-opacity doesn't work for icons
- [x] @ansis some tiles never load https://github.com/mapbox/llmr/issues/402
