### ISSUE TITLE
Rename this repo to "mapbox-gl"

### ISSUE THREAD

**Issue by lucaswoj** [mapbox/mapbox-gl-js#4070]
## Todo

- [x] move all issues from `mapbox-gl` to this repo
- [ ] rename this repo to `mapbox-gl`
- [ ] set up redirects from `mapbox-gl-js` website to `mapbox-gl` website

**Comment by 1ec5** [comment]
Are you considering rewording the README.md to serve as a landing page for all of Mapbox GL, as we had in the original mapbox/mapbox-gl readme? It would be very valuable to have a place to link to as Mapbox GL’s homepage – there currently is no such page. If we do that, though, could we reorganize this repository a bit, moving most of the GL JS–specific files into js/ (and the existing js/ into js/js/)?

**Comment by lucaswoj** [comment]
Yes to all of those ideas @1ec5 😄

**Comment by mollymerp** [comment]
Why are we renaming this repo to `mapbox-gl` when `mapbox-gl-native` is not part of this monorepo?

**Comment by lucaswoj** [comment]
@mollymerp Because this repo now contains code & issues shared between both Mapbox GL implementations. It is the central hub of the GL ecosystem.

**Comment by andrewharvey** [comment]
I like the current approach where `Mapbox GL JS` specifically refers to this JavaScript library, if this repo and the website does a `s/mapbox-gl-js/mapbox-gl/g` then it fragments how people refer to this JavaScript library.

**Comment by jfirebaugh** [comment]
Seems like the status quo (repo named "mapbox-gl-js") is working satisfactorily. Since renaming would be disruptive, at least temporarily, let's table it for now.
