### ISSUE TITLE
Master ticket tracking expression API completeness

### ISSUE THREAD

**Issue by anandthakker** [mapbox/mapbox-gl-js#6484]
This ticket is intended to define what set of operators would constitute a "complete" expression API and track its implementation.  

 - Math https://github.com/mapbox/mapbox-gl-js/issues/5853
   - [ ] All the `Math.*` functions from Javascript
   - [ ] All the relevant functions from `NSExpression` 
   - [ ] `is-nan` https://github.com/mapbox/mapbox-gl-js/issues/5494
 - Geo
   - [ ] Haversine distance https://github.com/mapbox/mapbox-gl-js/issues/6062
 - Color
   - [ ] All the color-modifying functions from CSS4 https://github.com/mapbox/mapbox-gl-js/issues/5676
 - Arrays
   - [ ] Construction https://github.com/mapbox/mapbox-gl-js/issues/6155
   - [ ] Search https://github.com/mapbox/mapbox-gl-js/issues/6473
   - [ ] Slicing
 - Strings
   - [ ] Search https://github.com/mapbox/mapbox-gl-js/issues/4113 (but see also Regular Expressions)
   - [ ] Replace https://github.com/mapbox/mapbox-gl-js/issues/4100 (but see also Regular Expressions)
   - [ ] Slicing
 - [ ] Regular Expressions https://github.com/mapbox/mapbox-gl-js/pull/6228
 - Locale and language
   - [ ] Test for script support https://github.com/mapbox/mapbox-gl-js/issues/5807
   - [ ] Case and diacritic folding https://github.com/mapbox/mapbox-gl-js/issues/4136

**Comment by 1ec5** [comment]
Inspired by this issue, I attempted to compile a similar issue to track feature parity with NSPredicate and NSExpression: mapbox/mapbox-gl-native#11786.

**Comment by gorshkov-leonid** [comment]
Hi, I have not found 
1. toHex(or toString(16)) 
1. substrig to save to variable
1. variable(set) / object(set) / array(s**p**lice)
1. how about supporting #FFFFFFFF(8 bytes) from [css4 ](http://dev.w3.org/csswg/css-color/#hex-notation)

**Comment by stevage** [comment]
Oh, I didn't know about this ticket!

Me, I would love more string-handling functions:

- left
- right
- split
- titlecase (yes I know it's difficult to do in a locale-independent way)

**Comment by lbutler** [comment]
> Oh, I didn't know about this ticket!
> 
> Me, I would love more string-handling functions:
> 
> * left
> * right
> * split
> * titlecase (yes I know it's difficult to do in a locale-independent way)

@stevage, just letting you know that my PR #9450 was merged in and soon you will have `slice` which you can use on strings to do left/right/mid. Check out #9443 to see some examples.

It's not perfect but if you had just a single word you could always slice the first letter and uppercase it and concat with the remainder of the string, something like the below (untested!)

`['concat', ['upcase', ['slice', ['get','attributeToTitleCase'], 0 ,1]],  ['downcase', ['slice', ['get','attributeToTitleCase'], 1]]]`

**Comment by FinnRG** [comment]
@mourner We extended mapbox-gl with a few basic date functions (new datetype, epoch: int -> date, hour and minute to get those values from a date value). Those are obviously pretty specific for our use case, but I could dedicate time to implement a more general date API. 

My questions would be:
- Is such an extension desired by the mapbox team?
- What should the API surface look like? (Timezone handling, date formats, etc.)
- Is a port of these APIs to the react native SDK a minimum requirement?

**Comment by miladhp** [comment]
Any updates for Date and time?
